### ISSUE TITLE
Uneven or unclear sample sizes 

### ISSUE THREAD

**Issue by Barryacoughlan** [hauselin/esconvert#1]
Hi Hauselin, 

I was hoping to use your fantastic effect size calculator to help convert a series of different effect sizes to fishers z and cohen's d for an umbrella review. I note that the tools states "All conversions assume equal-sample-size groups". In my case it's often unclear how many participants were in the treatment and control. Instead the reviews tend to present overall number of participants and the effect sizes. 

I was wondering if you could advise whether you think that your tool would be accurate for this use-case? Else if there was some other method you might suggest I would be massively appreciative. 

Sorry for sending this as a GitHub issue but I couldn't find your email address. 

Thanks so much in advance. 

With best wishes,

Barry 
Dr Barry Coughlan 
Postdoctoral researcher 
University of Cambridge

**Comment by hauselin** [comment]
I don't know if there's anything you can do if you don't have the no. of participants in each group. If the numbers aren't too different, then you should be fine assuming equal-sample-size groups. But if they do differ quite a bit, then the estimates will be biased. Not sure if there's much you can do since you just don't have the info. 

Maybe email the authors to get the actual sample sizes for each group and then use the appropriate conversion formulae for that (the references included on my site should provide all the relevant formulae)?

**Comment by Barryacoughlan** [comment]
Thanks so much for your advice Hause.

From: Hause Lin ***@***.***>
Reply to: hauselin/esconvert ***@***.***>
Date: Wednesday 8 June 2022 at 00:29
To: hauselin/esconvert ***@***.***>
Cc: Barry Coughlan ***@***.***>, Author ***@***.***>
Subject: Re: [hauselin/esconvert] Uneven or unclear sample sizes (Issue #1)


I don't know if there's anything you can do if you don't have the no. of participants in each group. If the numbers aren't too different, then you should be fine assuming equal-sample-size groups. But if they do differ quite a bit, then the estimates will be biased. Not sure what you can do here.

Maybe email the authors to get the actual sample sizes for each group and then use the appropriate conversion formulae for that (the references included on my site should provide all the relevant formulae)?

**Comment by liqingbioinfo** [comment]
Hi Hause,
     
     Thank you so much for providing such an amazing and useful tool. In my case, I want to convert the odds ratios to effect size, and my case : control is approximately 13:20. What kind of adjustment should I apply to effect sizes calculated by your program, given my unbalanced case-control samples? Any suggestions and comments are highly appreciated!

Yours sincerely
Leah

**Comment by hauselin** [comment]
Hi @liqingbioinfo, this paper might be helpful or should have relevant references.

Sánchez-Meca, J., Marín-Martínez, F., & Chacón-Moscoso, S. (2003). Effect-size indices for dichotomized outcomes in meta-analysis. Psychological Methods, 8(4), 448-467.

**Comment by liqingbioinfo** [comment]
Hi Hause
     
    I appreciate your prompt reply and will read that paper later.
